### ISSUE TITLE
Bug in Barchart

### ISSUE THREAD

**Issue by Folcon** [cljfx/cljfx#73] opened 2020-05-28 00:51 UTC
Hey,

Great library =)...

I was playing around with [example 28](https://github.com/cljfx/cljfx/blob/master/examples/e28_canvas.clj) and found this odd behaviour:
<img width="163" alt="Screenshot 2020-05-28 at 01 48 40" src="https://user-images.githubusercontent.com/123055/83086062-a191c180-a085-11ea-8edf-767d17a52110.png">
If I put in 25 items the labels appear, but at 26 or more the 2nd from the first and 2nd from the last labels are missing?

Not sure what to make of it...

**Comment by vlaaad** [comment] 2020-05-28 05:45
Hi! I think that's intended behavior of javafx when some of the labels don't fit — they will show if you make a chart bigger, for example, by resizing the window.

**Comment by Folcon** [comment] 2020-05-28 10:55
You're right, I can't believe I didn't think to try resizing the pane.

That's a really strange design decision to use text that doesn't work uniformly, or not to failover to a smaller symbol or indicator that there's something there?

Is there someway that I can override this with different behaviour? I'm not familiar with `javafx` =)...

**Comment by vlaaad** [comment] 2020-05-28 11:27
You can target these labels with CSS selector to make them smaller:
```css
.axis > Text {
  -fx-font-size: 10;
}
```
I don't think there is a way to override this behavior, I think this is one of the downsides of JavaFX — usually, it's very hard to override default behaviors of components.

**Comment by Folcon** [comment] 2020-05-28 12:18
@vlaaad Thanks for the tip =)...

Is there anything like responsive in css that would allow me to just declare styles for different sizes?

**Comment by vlaaad** [comment] 2020-05-28 12:29
Not sure I understand your question, do you mean media queries for different screen sizes? In that case, no, there are no media queries. You should look at [javafx css reference](https://openjfx.io/javadoc/14/javafx.graphics/javafx/scene/doc-files/cssref.html) to see what's there in javafx's css.

**Comment by vlaaad** [comment] 2020-05-28 12:31
I would also recommend using [cljfx/css](https://github.com/cljfx/css) library instead of css files — much better experience!

**Comment by Folcon** [comment] 2020-05-28 13:01
Thanks =)...

I'll have a look.

Is something like media queries out of scope? Or do people tend to just hack their own solution / just use fixed screen sizes?

Just trying to get an understanding about how it all works =)...

**Comment by vlaaad** [comment] 2020-05-28 13:28
I use resizable window without media queries :)

There are fine layout components that help to make responsive layout without media queries: v-box, h-box, grid-pane etc.

Adding media queries is out of scope for cljfx: its purpose is providing declarative API to javafx, not building on top of it.

**Comment by Folcon** [comment] 2020-05-28 14:53
Cool, I'll see if I can work it out! Thanks =)...

**Comment by vlaaad** [comment] 2020-05-28 15:03
You are welcome!

**Closed by vlaaad** 2020-05-28 15:03 UTC
Labels: javafx
