### ISSUE TITLE
Suggestions for diagnosing a memory leak

### ISSUE THREAD

**Issue by geokon-gh** [cljfx/cljfx#78] opened 2020-07-07 10:29 UTC
I've noticed my app will slowly eat more and more memory till after a few Gigs my system runs out and the application crashes

My state atom seems to match the correct invocation:

``` clojure

(def *context
  ""
  (atom (fx/create-context {:my-map "with-lots-of-stuff"}
                           cache/lru-cache-factory))
```

But the memory usage seems to keep inching up and up

At least superficially the cache does seems to work. I will very consistently get cache misses and values seem to be constantly recalculated. In fact I'd say way too often.. The application runs much faster and is much more responsive without the cache though that would definitely leave me with a memory leak :)

But at the moment I have a cache and I have a memory leak!

Do you have any suggestions as to how to diagnose the issue? I've never really come across this before and I don't know which JVM tools to use (or maybe I need to somehow tune `cache/lru-cache-factory` ?)

**Comment by vlaaad** [comment] 2020-07-10 21:58
Hi!
You can start by inspecting the cache with `(count (into {} @(:cljfx.context/*cache @*context)))` from time to time. It should be stuck on 32 (default lru limit which is too small and can be bumped for example by using this as cache factory: `#(cache/lru-cache-factory % :threshold 4096)`)
Usually, on the JVM memory issues or investigated with profilers like visualVM (free, by oracle) or YourKit (paid, but I think there is an evaluation period). 
Moving on to Clojure land, you can use [clj-memory-meter](https://github.com/clojure-goes-fast/clj-memory-meter) in the repl to see how much memory the `*context` really consumes. I'd probably start with this.

**Comment by geokon-gh** [comment] 2020-07-13 06:31
Hey Vlaaad,

I just wanted to again thank you for the help :))

I'll write down what I needed to do here just as a guide for anyone else that comes along:
- You add the `clj-memory-meter` tool to your application by adding this to your dependencies
``` clojure
  com.clojure-goes-fast/clj-memory-meter {:mvn/version "0.1.2"}
```
- To get it working you need to inject a JVM option into the CIDER launch. So in emacs I added/modified this ELisp variable
``` elisp
(setq cider-clojure-cli-global-options "-J-Djdk.attach.allowAttachSelf")
```
Now you can launch a REPL and in your namespace you can test it works by running 
``` clojure
(clj-memory-meter.core/measure "hello")
```
and it should print out some value (if the previous step didn't work you will get an error here)

Then at this point you can't measure the context directly. This will throw an error
``` clojure
(mm/measure state/*context)
;; Execution error (InaccessibleObjectException) at java.lang.reflect.AccessibleObject/checkCanSetAccessible (AccessibleObject.java:349).
;; Unable to make field public final jdk.javadoc.internal.tool.ElementsTable jdk.javadoc.internal.tool.DocEnvImpl.etable accessible: module jdk.javadoc does not "exports jdk.javadoc.internal.tool" to unnamed module @4eeecfd0
```
Instead, you need to dig out the cache itself
``` clojure
(mm/measure (into {} @(:cljfx.context/*cache  @state/*context)))
```
After loading my data I got something like 2.2MB. I played around with my GUI and made the memory usage balloon and the cache stayed at 2.2MB. So this was a good sanity check that it's not actually a cache issue at all

I also managed to remove some piece of code from my project and isolate the issue to SVG drawing. If the SVG plots are removed then the project has stable memory usage (it's still a crazy ~150MB, but it's manageable). I can also consistently cause memory spikes by making the SVG redraw a lot (by zooming in an out of the image rapidly). At this point I'm pretty sure it's an issue with how I'm using SVGSalamander

Next I ran the VisualVM tool. It's quite handy b/c it can just inspect a running process and you don't need to modify the project or work environment. This didn't tell me much directly. There is no equivalent to a call graph for memory usage, so you mostly get a huge list of java/clojure base library objects. The heap was seemingly taken up by `byte[]` instances - but who knows from where exactly

However, the one thing I noticed is that VisualVM allows me to smack a "Perform GC"  button. Whenever I hit that, almost all the memory gets freed up and it drops back down to the ~200MB range. I'm still seeing memory usage creep - but not app-crashing amounts (and maybe it's asymptotic). However at this point I'm not sure how the garbage collector is being blocked from naturally running in the applications. It seems I have 2 issues, garbage collector not collecting, and the SVG renderer going a little crazy with memory usage

Will post an update when I found out more! Thanks again

**Comment by geokon-gh** [comment] 2020-07-15 08:05
![memleak](https://user-images.githubusercontent.com/21017379/87514065-40ad5f80-c6ac-11ea-9f15-c71893f0eee7.png)
I got this amusing sawtooth graph after I left for lunch and came back

Another useful tool has been the Eclipse Memory Analyzer. It quite similar to VisualVM but has some additional automated "problem finder" utility which gave me back 2 problematic objects:

Some hash map (maybe the cache?)

java.util.WeakHashMap @ 0x85b0c398 | 48 | 26,073,232 | 30.30%
-- | -- | -- | --
java.util.WeakHashMap$Entry[32] @ 0xa313d320 | 144 | 26,073,136 | 30.30%
java.nio.HeapByteBuffer @ 0xa3101010 | 56 | 24,438,312 | 28.40%
byte[24438240] @ 0x8dd00000 .................................................................................................

and an image


hb java.nio.HeapByteBuffer @ 0xa3100038 | 56 | 31,842,792
-- | -- | --
pixelBuffer com.sun.prism.Image @ 0xa3b00000 | 56 | 112
image com.sun.javafx.sg.prism.NGImageView @ 0x8638ea48 | 144 | 944
peer javafx.scene.image.ImageView @ 0x8638e780 | 296 | 1,288
arg$1 javafx.scene.Node$$Lambda$90 @ 0x8638e8a8 | 16 | 16
[156] javafx.beans.value.ChangeListener[472] @ 0x86c900b8 | 1,904 | 1,904
changeListeners com.sun.javafx.binding.ExpressionHelper$Generic @ 0x86095988 | 40 | 1,944
helper javafx.beans.property.ReadOnlyBooleanWrapper$ReadOnlyPropertyImpl @ 0x86095970 | 24 | 1,968
readOnlyProperty javafx.stage.Window$12 @ 0x86095940 | 48 | 2,016
showing javafx.stage.Stage @ 0x86095410 | 200 | 3,696
fxStage com.sun.javafx.tk.quantum.WindowStage @ 0x860c2088 | 72 | 304
stage com.sun.javafx.tk.quantum.GlassWindowEventHandler @ 0x860c2070 | 24 | 24
eventHandler com.sun.glass.ui.gtk.GtkWindow @ 0x860c1ec0 JNI Global | 160 | 184
stage com.sun.javafx.tk.quantum.ViewScene @ 0x860c20d0 » | 88 | 2,344
item java.util.LinkedList$Node @ 0x863889e8

But the totals are still quite small. It's 26MB and 31MB. The problem, I suspect, is loose objects on the heap that aren't getting cleaned up. I could be wrong though b/c peppering around some `(System/gc)` in places doesn't seem to fix the issue much for some reason. (though the VisualVM garbage collection buttons always seems to work well haha)

In keeping with the general functional nature of Clojure and the memoized way of doing things in CLJFX I end up regenerating Images. So if you scroll to zoom then you will quickly generate a sequence of images one after another (each tens of megabytes) and you won't be reusing the image buffers but actually generating new images. So the old images and intermediaries probably end up floating around in the heap. Each image might have some internal intermediaries, so I could see this being a couple hundred megabytes at each zoom level. 

I've both tried generating the image within a subscription and just having the `:image-view` calls the plotter/SVG-renderer directly (with no context/cache) - with identical behavior

I'd like to avoid having to make/reuse image buffers b/c it will muddle the code - but I may have no alternative

**Comment by vlaaad** [comment] 2020-07-15 08:30
Sawtooth pattern is an expected memory consumption of a JVM, this is fine! It seems the problem is with images, maybe there might be another approach to drawing svgs? I checked out the readme of svgsalamander, it says it does not depend on any particular rendering engine, maybe you can hook it into Canvas drawing of javafx? That way you don't recreate any images, only redraw shapes. Also, as far as I know, javafx supports some svg rendering natively, maybe that will suffice? Take a look at SVGPath, for example.

**Comment by geokon-gh** [comment] 2020-07-15 08:56
By hooking into the Canvas drawing of javafx do you mean writing my own SVG renderer? It seems involved and a bit of a rabbit hole of a project to implement. All the rendering functions expect a `Graphics2D` object and JavaFX doesn't seem to operate directly with `Graphics2D`

I'll take another look at the native SVG renderer! Thanks for the suggestion, it'd slipped my mind. Last I looked it seemed to have some arbitrary limitation and it implemented only part of the spec so I'd avoided it. My usecase at the moment is pretty simple though, so I guess I could revisit this at a later time if it became insufficient. Good idea :)

**Comment by vlaaad** [comment] 2020-07-15 09:16
Ah, I thought Graphics2D is a small interface that that library defines. By the way, I found this adapter from Graphics2D to javafx: https://github.com/jfree/fxgraphics2d

**Comment by geokon-gh** [comment] 2020-07-15 10:02
Oh great! Interesting library.

I found an example 
https://github.com/jfree/jfree-fxdemos/blob/master/src/main/java/org/jfree/fx/demo/FXGraphics2DDemo1.java
As most Java examples it's a bit overengineered, but I think the core mechanism is not too complicated. If I understand the Java correctly it shouldn't be too hard to massage that into the CLJFX workflow:

Maybe that would cut down on some of the overhead! Though it's all a bit strange b/c the JavaFX thread will need to do the rendering regardless.

I also just grabbed the thi-ng/geom internal SVG EDN-ish representation. It's a bit strange looking
<details>
<summary> and it seems to be organized mostly in nested vectors</summary>
[:g
 nil
 nil
 ([:polyline
   {:fill none,
    :stroke black,
    :stroke-width 1.25,
    :points 40.67,357.86 42.03,353.57 43.38,339.79 44.74,306.65 46.13,238.94 47.45,250.56 48.84,266.93 50.16,270.60 51.55,288.58 52.90,294.53 54.22,298.32 55.57,300.60 56.93,315.74 58.28,315.74 59.75,319.13 61.13,323.98 62.48,319.82 63.70,322.42 65.06,321.17 66.41,320.54 67.77,318.55 69.12,325.18 70.47,331.20 71.83,328.85 73.18,326.04 74.54,324.82 75.89,333.22 77.25,329.90 78.60,328.15 79.96,334.15 81.31,328.34 82.67,331.94 84.02,307.27 85.38,311.78 86.73,321.48 88.09,333.22 89.44,331.08 90.80,317.71 92.15,311.16 93.51,290.57 94.86,266.81 96.22,224.40 97.57,191.57 98.92,162.79 100.28,146.81 101.63,199.37 102.99,76.87 104.34,72.24 105.70,87.12 107.05,136.63 108.41,189.62 109.76,247.56 111.12,259.15 112.47,315.43 113.83,306.19 115.18,334.85 116.54,342.00 117.89,327.60 119.25,327.43 120.60,317.78 121.96,300.17 123.31,289.61 124.67,304.22 126.02,313.44 127.37,289.58 128.73,319.68 130.08,334.20 131.44,321.17 132.79,351.89 134.15,311.81 135.50,305.30 136.86,313.68 138.21,315.19 139.57,304.44 140.92,270.17 142.28,300.19 143.63,283.03 144.99,294.84 146.34,277.66 147.70,280.46 149.05,294.91 150.41,321.50 151.76,318.77 153.12,312.31 154.47,317.35 155.82,338.81 157.18,324.41 158.53,330.26 159.89,328.49 161.24,321.94 162.60,324.53 163.95,330.00 165.31,337.25 166.66,333.10 168.02,345.05 169.37,336.05 170.73,343.90 172.08,346.46 173.44,340.03 174.79,335.90 176.15,328.49 177.50,336.55 178.86,344.76 180.21,344.54 181.57,340.56 182.92,344.98 184.27,341.21 185.63,341.09 186.98,346.01 188.34,345.65 189.69,341.93 191.05,348.17 192.40,345.94 193.76,346.94 195.11,345.62 196.47,346.49 197.82,269.86 199.18,252.86 200.53,312.14 201.89,321.00 203.24,311.74 204.60,326.02 205.95,325.01 207.31,338.88 208.66,339.00 210.02,344.50 211.37,347.18 212.72,346.08 214.08,348.34 215.43,347.16 216.79,344.74 218.14,341.57 219.50,347.14 220.85,345.79 222.21,340.73 223.56,349.70 224.92,349.90 226.27,354.43 227.63,350.30 228.98,350.04 230.34,351.98 231.69,349.25 233.05,348.70 234.40,348.55 235.76,343.13 237.11,343.13 238.47,337.73 239.82,335.04 241.17,347.35 242.53,348.60 243.88,350.02 245.24,347.59 246.59,349.32 247.95,346.27 249.30,346.32 250.66,346.08 252.01,347.21 253.37,344.18 254.72,342.58 256.08,308.09 257.43,344.26 258.79,345.10 260.14,345.17 261.50,344.40 262.85,340.63 264.21,286.94 265.56,323.45 266.92,334.63 268.27,329.18 269.62,331.63 270.98,334.46 272.33,340.75 273.69,320.95 275.04,323.09 276.40,320.28 277.75,336.10 279.11,334.03 280.46,335.26 281.82,340.06 283.17,337.15 284.53,340.22 285.88,342.05 287.24,333.58 288.59,331.06 289.95,334.87 291.30,330.58 292.66,340.80 294.01,343.06 295.37,344.86 296.72,335.86 298.07,339.60 299.43,339.89 300.78,342.43 302.14,338.40 303.49,336.98 304.85,268.32 306.20,320.40 307.56,312.86 308.91,306.14 310.27,308.98 311.62,302.93 312.98,302.14 314.33,309.14 315.69,303.84 317.04,309.19 318.40,297.50 319.75,303.05 321.11,301.03 322.46,292.92 323.82,291.96 325.17,261.12 326.52,298.30 327.88,290.11 329.23,297.91 330.59,315.82 331.94,275.88 333.30,300.74 334.65,282.91 336.01,309.29 337.36,323.98 338.72,302.14 340.07,307.15 341.43,300.65 342.78,306.05 344.14,234.84 345.49,290.11 346.85,343.85 348.20,355.13 349.56,354.46 350.91,355.46 352.27,353.71 353.62,354.50 354.97,353.83 356.33,352.73 357.68,352.06 359.04,353.95 360.39,354.26 361.75,355.25 363.10,353.62 364.46,353.76 365.81,351.38 367.17,352.32 368.52,352.46 369.88,353.28 371.23,351.70 372.59,350.76 373.94,352.82 375.30,352.56 376.65,351.50 378.01,346.44 379.36,352.08 380.72,352.03 382.07,351.29 383.42,351.77 384.78,351.65 386.13,350.95 387.49,351.02 388.84,352.34 390.20,351.98 391.55,352.27 392.91,350.93 394.26,349.54 395.62,350.78 396.97,350.04 398.33,349.20 399.68,350.59 401.04,351.72 402.39,350.90 403.75,349.58 405.10,351.89 406.46,348.36 407.81,360.00 409.17,360.00 410.52,359.74 411.87,360.00}])
 [:g
  {:stroke none}
  ([:line
    {:x1 0.00, :y1 0.00, :x2 0.00, :y2 10.00}]
   [:line
    {:x1 135.48, :y1 0.00, :x2 135.48, :y2 10.00}]
   [:line
    {:x1 270.95, :y1 0.00, :x2 270.95, :y2 10.00}]
   [:line
    {:x1 406.43, :y1 0.00, :x2 406.43, :y2 10.00}])
  nil
  [:g
   {:stroke none, :fill dimgray, :font-family nil, :font-size 10, :text-anchor middle}
   [:text
    {:x 0.00, :y 359.00}
    0.00]
   [:text
    {:x 135.48, :y 359.00}
    500.00]
   [:text
    {:x 270.95, :y 359.00} 1000.00]
   [:text
    {:x 406.43, :y 359.00} 1500.00]]
  [:line
   {:x1 0.00, :y1 0.00, :x2 415.78, :y2 0.00}]]
 [:g
  {:stroke black}
  ([:line
    {:x1 0.00, :y1 360.00, :x2 -5.00, :y2 360.00}]
   [:line
    {:x1 0.00, :y1 240.00, :x2 -5.00, :y2 240.00}]
   [:line
    {:x1 0.00, :y1 120.00, :x2 -5.00, :y2 120.00}]
   [:line
    {:x1 0.00, :y1 0.00, :x2 -5.00, :y2 0.00}])
  nil
  [:g
   {:stroke none, :fill dimgray, :font-family nil, :font-size 10, :text-anchor middle}
   [:text
    {:x 25.00, :y 370.00} 0.00]
   [:text {:x 25.00, :y 250.00} 5000.00]
   [:text {:x 25.00, :y 130.00} 10000.00]
   [:text {:x 25.00, :y 10.00} 15000.00]]
  [:line {:x1 0.00, :y1 360.00, :x2 0.00, :y2 0.00}]]]
<\details>

But it shouldn't be too difficult to traverse and made a nested CLJFX tree out of.. I hope!

thi-ng/geom has some really good docs, so I'll need to dig around and see the full scope of things I'd need to support. It might be manageable :)

**Comment by geokon-gh** [comment] 2020-07-18 11:22
Oh man, using native SVGPath/Line/Text primitives not only eliminated the memory issues but made the whole application silky smooth. It's so much better now. Thank you so much for encouraging me to implement that

The code ended up being quite short. I'm just parsing SVG hiccup and massaging the values into CLJFX maps

I still haven't implemented the styling/attribute stuff yet. I think it'll take a little bit of futzing around and there will be corner cases.. I think the attribute inheritance works a bit different. For instance the JFX Group Node is not equivalent to an SVG Group. So a SVG Group could have a stroke-width set at the Group level while in JFX you'd need to propagate that manually to all the Group's shapes (when applicable) b/c unused props make CLJFX upset

Btw, I like the current library syntax, but why not use hiccup? Does it just end up looking uglier? (Not that you need to output FXML, but it's a bit "standard")

Thanks as always for your help,
I probably couldn't have done this without it :)
And thank you for putting up with my issues

**Comment by vlaaad** [comment] 2020-07-18 12:08
Glad you figured it out! Perhaps you can buy me a beer if I'll ever visit China 😉
Maybe you can implement style "inheritance" using function components by passing style information from component props to children props?

Early stages of cljfx used hiccup markup, but it wasn't very clear, because javafx node graph is not like xml that allows any node to have children. What are `:stage`'s children, scenes? But stage can have only one scene... It's just a wrong metaphor, because the underlying model is different. I also find maps more easily editable — adding a prop programmatically is just `assoc`, modifying is just `update` etc.

**Comment by vlaaad** [comment] 2020-07-18 12:10
I also don't like that cljfx rejects unknown props, maybe I'll make it ignore them...

**Comment by geokon-gh** [comment] 2020-07-19 08:22
Yeah, I see your point, and it's true for XML in general, but it actually matches what happens in HTML. HTML elements can also be forbidden from have children:
https://developer.mozilla.org/en-US/docs/Glossary/empty_element

For instance if you have an image tag

```html
<img src="some-url.png">
```
Then it has attributes but no children

I guess the issue in a sense is that hiccup makes it easy to write some nonesense :)

And you're right it's a bit less nice to modify, With `(assoc-in [..] ..) you can access vector fields as easily as map fields, but if you wanna change all the children it's not just (assoc-in [... :children] new-stuff). Instead you have to somehow swap the tail of a vector. Maybe that's easy too? but I can't think of it off the top of my head.

I spent part of today converting SVG attributes to JFX shape props and I've got to say that they are mostly one-to-one. Either the JFX designers bases it off SVG directly or SVG and JFX are both based off some common standard. There are a few minor exceptions, but generally speaking they're identical.. with `fill`, `stroke-width`, `stroke-dash-array` etc. etc.  I just needed to handle some edge cases and things like `nil`/`none` fields and fonts and it all was working

And yeah, I'm in Taiwan now, so if you ever do come by these parts, do let me know :)
The best I could do is give you an acknowledgement on the webpage: https://geokon-gh.github.io/corascope/

**Comment by vlaaad** [comment] 2020-07-19 19:03
Haha, nice, thanks for acknowledging :)
By the way, I couldn't try this app because example scan links give me 404.

Closing this one since it seems to be resolved, feel free to open more 😄

**Closed by vlaaad** 2020-07-19 19:03 UTC

**Comment by geokon-gh** [comment] 2020-07-21 08:28
Thanks for that catch! Links fixed :)

**Comment by geokon-gh** [comment] 2020-07-21 09:20
And thanks for the tip on `ask.clojure`!
